Login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    
    #프로필 링크
    path('users/<int:user_id>', 
        views.ProfileView.as_view(), 
        name='profile'),
    
    #프로필 설정
    path('set-profile/', 
        views.ProfileSetView.as_view(), 
        name='profile-set'),
    
    #프로필 수정
    path('edit-profile/', 
        views.ProfileUpdateView.as_view(), 
        name='profile-update'),

]

config/urls.py
from django.contrib import admin
from django.urls import path ,include
from Login.views import CustomPasswordChangeView
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    #admin
    path('admin/', admin.site.urls),

    #calendar
    path('calendar/', include('emotion_calendar.urls')),
    
    #Diary
    path('diary/', include('diary.urls')),
    
    #Login
    path('', include('Login.urls')),
    
    # 이메일 재인증
    path(
        'email-confirmation-required/',
        TemplateView.as_view(template_name='account/email_confirmation_required.html'),
        name='account_email_confirmation_required',
    ),
    # 이메일 변경
    path(
        'email-confirmation-done/',
        TemplateView.as_view(template_name='account/email_confirmation_done.html'),
        name='account_email_confirmation_done',
    ),
    # 비밀번호 변경
    path(
        'password/change/',
        CustomPasswordChangeView.as_view(),
        name = "account_change_password"),
    path('', include('allauth.urls')),

]
# 개발 모드에서만 디버그, 배포에서는 동작 안함
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

emotion_calendar/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'cal'
urlpatterns = [
    url('', views.CalendarView.as_view(), name='calendar'),


    # url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

emotion_calendar/models.py
# from django.db import models
# from django.urls import reverse

# class Event(models.Model):
#     title = models.CharField(max_length=200)
#     description = models.TextField()
#     start_time = models.DateTimeField()
#     end_time = models.DateTimeField()

#     @property
#     def get_html_url(self):
#         url = reverse('cal:event_edit', args=(self.id,))
#         return f'<a href="{url}"> {self.title} </a>'

emotion_calendar/forms.py
# from django.forms import ModelForm, DateInput
# from emotion_calendar.models import Event

# class EventForm(ModelForm):
#   class Meta:
#     model = Event
#     # datetime-local is a HTML5 input type, format to make date time show on fields
#     widgets = {
#       'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
#       'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
#     }
#     fields = '__all__'

#   def __init__(self, *args, **kwargs):
#     super(EventForm, self).__init__(*args, **kwargs)
#     # input_formats parses HTML5 datetime-local input to datetime field
#     self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
#     self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

emotion_calendar/views.py
from datetime import datetime, timedelta, date
from django.views import generic
from django.utils.safestring import mark_safe
import calendar
from .utils import Calendar
from diary.models import Diary
from Login.models import User
import json
from braces.views import LoginRequiredMixin
# wordCloud
from wordcloud import WordCloud
class CalendarView(LoginRequiredMixin, generic.ListView):
    model = Diary
    template_name = 'emotion_calendar/calendar.html'
    context_object_name = 'diarys'

    def get_context_data(self, **kwargs):
        # diarys = Diary()

        context = super().get_context_data(**kwargs)
        
        d = get_date(self.request.GET.get('month', None))
        diarys = Diary.objects.filter(author=self.request.user, dt_created__month=d.month)
        
        # 이번달 전체 일기 내용 워드 클라우드 만들기
        this_month_diary = ""
        for i in range(len(diarys)):
            this_month_diary += diarys[i].content
            this_month_diary += ' '
        if this_month_diary != "":
            wc = WordCloud(font_path='static/YdestreetB.ttf', width=600, height=600, scale=2.0, max_font_size=250)
            gen = wc.generate(this_month_diary)
            f_name = str(self.request.user).split('.')[0]
            full_name = 'static/'+ f_name +'.png'
            gen.to_file(full_name)
            down_name = '/../static/'+ f_name +'.png'
            context['img_path'] = down_name
        else:
            context['img_path'] = ''

        # 이번달 감정 결과 그래프 만들기
        # month_len = [0,31,28,31,30,31,30,31,31,30,31,30,31]
        if len(diarys) != 0:
            month_len = calendar.monthrange(d.year,d.month)
            happy = [0] * (month_len[1]+1)
            normal = [0] * (month_len[1]+1)
            sad = [0] * (month_len[1]+1)
            angry = [0] * (month_len[1]+1)
            anxiety = [0] * (month_len[1]+1)
            jsonDec = json.decoder.JSONDecoder()
            for i in range(len(diarys)):
                ind = int(str(diarys[i].dt_created).split('-')[2])
                emotion_val_calendar = jsonDec.decode(diarys[i].emotion_value)
                happy[ind] = float(emotion_val_calendar[4])
                normal[ind] = float(emotion_val_calendar[3])
                sad[ind] = float(emotion_val_calendar[2])
                angry[ind] = float(emotion_val_calendar[1])
                anxiety[ind] = float(emotion_val_calendar[0])
            #     labels = [i for i in range(1, month_len[1]+1)]
            # context['happy'] = happy[1:]
            # context['normal'] = normal[1:]
            # context['sad'] = sad[1:]
            # context['angry'] = angry[1:]
            # context['anxiety'] = anxiety[1:]
            # context['labels'] = labels
            context['happy'] = sum(happy[1:])/len(diarys)
            context['normal'] = sum(normal[1:])/len(diarys)
            context['sad'] = sum(sad[1:])/len(diarys)
            context['angry'] = sum(angry[1:])/len(diarys)
            context['anxiety'] = sum(anxiety[1:])/len(diarys)
        else:
            context['happy'] = 0
            context['normal'] = 0
            context['sad'] = 0
            context['angry'] = 0
            context['anxiety'] = 0

        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(self.request.user, withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

class wordCloudView(generic.DetailView):
    model = User
    template_name = "emotion_calendar/calendar.html"
    pk_url_kwarg = 'user_id'
    context_object_name = "profile_user"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs.get('user_id')
        context['user_diary'] = Diary.objects.filter(author__id = user_id).order_by("-dt_created")[:4]
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

emotion_calendar/templates/emotion_calendar/calendar.html
{% extends "base/navbar.html" %}

{% block navi %}
  <li><a class="nav-link" data-toggle="modal" data-target="#myModal">이번 달 나는?</a></li>
{% endblock navi %}

{% load static %}
{% block content %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="{% static 'emotion_calendar/css/calender_styles.css' %}?3ff1">
  <title>SketchDay</title>
</head>

<body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

<link rel="stylesheet" type="text/css" href="{% static 'emotion_calendar/css/calender_styles.css' %}?1">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
crossorigin="anonymous"></script>
{% if messages %}
  {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible alert-warning">
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
              <h4 class="alert-heading">{{ message.tag }}</h4>
              <p class="mb-0">{{ message.tag }}{{ message }}</p>
      </div>
  {% endfor %}
{% endif %}
<script>
  window.setTimeout(function() {
    $(".alert-dismissible").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove();
    });
}, 2000);
</script>
  <div class="container mt-4 mb-4">
    <div class="row">
      <div class="col-sm-12">
        <div> 
          <div style="float: left; width: 5%; margin-top: 25%;">
            <a class="btn" href="{% url 'cal:calendar' %}?{{ prev_month }}" style="font-size: 3rem"> < </a>
          </div>
          <div style="float: left; width: 90%">
            {{ calendar }}
          </div>
          <div style="float: left; width: 5%;  margin-top: 25%;">
            <a class="btn" href="{% url 'cal:calendar' %}?{{ next_month }}" style="font-size: 3rem"> > </a>
          </div>
        </div>
      </div>
    </div>
    
  </div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-fullsize" role="document">
    <div class="modal-content modal-fullsize">
      <div class="modal-header">
        <h4 class="modal-title center" id="myModalLabel">이번 달 나는?</h4>
        <button type="button" class="close right" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        
      </div>
      <div class="modal-body">
        <div>
          <p>워드 클라우드</p>
          <center><img src="{{ img_path }}" style="width:250px; height:250px;"></center>
        </div>
        <div>
          <p>감정선</p>
          <canvas id="monthChart"></canvas>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">닫기</button>
      </div>
    </div>
  </div>
</div>
<script>
  var emotion_line = document.getElementById('monthChart').getContext('2d');
  var emotionLineChart = new Chart(emotion_line, {
      type: 'bar',
      // data:{
      //   labels: {{ labels }},
      //   datasets: [{
      //       label: '행복',
      //       data: {{ happy }},
      //       borderColor: "#f7323f",
      //       lineTension: 0,
      //   },{
      //         label: '평온',
      //         data: {{ normal }},
      //         borderColor: "#673ba7",
      //         lineTension: 0,
      //   },{
      //         label: '슬픔',
      //         data: {{ sad }},
      //         borderColor: "#ff6384",
      //         lineTension: 0,
      //   },{
      //         label: '분노',
      //         data: {{ angry }},
      //         borderColor: "#cc65fe",
      //         lineTension: 0,
      //   },{
      //         label: '불안',
      //         data: {{ anxiety }},
      //         borderColor: "#ffce56",
      //         lineTension: 0,
      //   }]
      // }
      data:{
        labels: ['기쁨', '평온', '슬픔', '화남', '불안'],
        datasets: [{
            label: '이번달 총 감정지수',
            data: [{{ happy }}, {{ normal }}, {{ sad }}, {{ angry }}, {{ anxiety }}],
            backgroundColor: [
            'rgba(255, 99, 132, 0.2)',
            'rgba(255, 159, 64, 0.2)',
            'rgba(255, 205, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(54, 162, 235, 0.2)',
          ],
          borderColor: [
            'rgb(255, 99, 132)',
            'rgb(255, 159, 64)',
            'rgb(255, 205, 86)',
            'rgb(75, 192, 192)',
            'rgb(54, 162, 235)',
          ],
          borderWidth: 1,
        }]
      },
      options: {
        indexAxis: 'y',
      }
  });

</script>
{% endblock content %}